//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BACnet.Client.Db {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Queries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Queries() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BACnet.Client.Db.Queries", typeof(Queries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-- contains a single record to indicate the current schema version
        ///
        ///CREATE TABLE Version (
        ///	version				VARCHAR(255) NOT NULL
        ///);
        ///
        ///INSERT INTO Version(version) VALUES(&apos;v0.3&apos;);
        ///
        ///-- contains a record for each object on the network
        ///
        ///CREATE TABLE Objects (
        ///	device_instance		UNSIGNED INTEGER NOT NULL,
        ///	object_type			UNSIGNED INTEGER NOT NULL,
        ///	instance			UNSIGNED INTEGER NOT NULL,
        ///	vendor_id			UNSIGNED INTEGER NOT NULL,
        ///	name				VARCHAR(255) NULL,
        ///	props				VARCHAR(4096) NULL,
        ///	last_refresh		DAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateSchema {
            get {
                return ResourceManager.GetString("CreateSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT
        ///	*
        ///FROM Objects
        ///WHERE
        ///	device_instance = @deviceInstance AND
        ///	object_type = @objectType AND
        ///	instance = @instance;.
        /// </summary>
        internal static string GetObject {
            get {
                return ResourceManager.GetString("GetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///SELECT
        ///	device_instance,
        ///	object_type,
        ///	instance
        ///FROM Objects
        ///WHERE
        ///	last_refresh &lt; @lastRefreshThreshold AND
        ///	last_refreshed &lt; @lastRefreshedThreshold
        ///ORDER BY device_instance, object_type, instance
        ///LIMIT @limit;
        ///
        ///UPDATE Objects
        ///SET
        ///	last_refresh = DATETIME(&apos;now&apos;)
        ///WHERE
        ///	last_refresh &lt; @lastRefreshThreshold AND
        ///	last_refreshed &lt; @lastRefreshedThreshold
        ///ORDER BY device_instance, object_type, instance
        ///LIMIT @limit;.
        /// </summary>
        internal static string GetQueuedRefreshes {
            get {
                return ResourceManager.GetString("GetQueuedRefreshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT version FROM version;.
        /// </summary>
        internal static string GetVersion {
            get {
                return ResourceManager.GetString("GetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM Objects
        ///WHERE
        ///	device_instance = COALESCE(@deviceInstance, device_instance) AND
        ///	object_type = COALESCE(@objectType, object_type);.
        /// </summary>
        internal static string QueryObjects {
            get {
                return ResourceManager.GetString("QueryObjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT COUNT(*) FROM sqlite_master WHERE type = &apos;table&apos; AND name = @tableName;.
        /// </summary>
        internal static string TableExists {
            get {
                return ResourceManager.GetString("TableExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///UPDATE Objects
        ///SET
        ///	name = @name,
        ///	props = @props,
        ///	last_refresh = DATETIME(&apos;now&apos;),
        ///	last_refreshed = DATETIME(&apos;now&apos;)
        ///WHERE
        ///	device_instance = @deviceInstance AND
        ///	object_type = @objectType AND
        ///	instance = @instance;.
        /// </summary>
        internal static string UpdateObject {
            get {
                return ResourceManager.GetString("UpdateObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///INSERT OR IGNORE INTO Objects(
        ///	device_instance, 
        ///	object_type,
        ///	instance,
        ///	vendor_id
        ///) VALUES (
        ///	@deviceInstance,
        ///	@objectType,
        ///	@instance,
        ///	@vendorId
        ///);.
        /// </summary>
        internal static string UpsertObject {
            get {
                return ResourceManager.GetString("UpsertObject", resourceCulture);
            }
        }
    }
}
